name: Pull Request Validation

on:
  pull_request:
    types:
      - opened

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Assign author to issue
        uses: toshimaru/auto-author-assign
        with:
          issue-number: ${{ env.ISSUE_NUMBER }}
          assignees: ${{ github.event.pull_request.user.login }}
      - name: Check if issue is assigned
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.title }}" | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
          if [ -z "${ISSUE_NUMBER}" ]; then
            echo "No issue is assigned to this pull request. Please assign an issue and try again."
            exit 1
          fi
